RedditOnRails/config/routes.rb
Rails.application.routes.draw do

  resources :posts
  resources :subs
  resources :users
  resource :session, only: [:new, :create, :destroy]


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

RedditOnRails/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RedditOnRails/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  url        :string
#  content    :string
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Post < ApplicationRecord
  validates :title, presence: true
  # validates :subs, length: { minimum: 1 }

  belongs_to :author,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :User

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :PostSub

  has_many :subs,
    through: :post_subs,
    source: :sub
end

RedditOnRails/app/models/post_sub.rb
# == Schema Information
#
# Table name: post_subs
#
#  id         :integer          not null, primary key
#  sub_id     :integer          not null
#  post_id    :integer          not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class PostSub < ApplicationRecord
  validates :sub_id, :post_id, presence: true

  belongs_to :post,
    primary_key: :id,
    foreign_key: :post_id,
    class_name: :Post

  belongs_to :sub,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :Sub
end

RedditOnRails/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  description  :string           not null
#  moderator_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Sub < ApplicationRecord
  validates :title, :description, :moderator_id, presence: true

  belongs_to :moderator,
    class_name: :User,
    primary_key: :id,
    foreign_key: :moderator_id

  has_many :post_subs,
    primary_key: :id,
    foreign_key: :sub_id,
    class_name: :PostSub

  has_many :posts,
    through: :post_subs,
    source: :post
end

RedditOnRails/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  session_token   :string           not null
#

class User < ApplicationRecord
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }
  before_validation :ensure_session_token

  attr_reader :password

  has_many :subs,
    primary_key: :id,
    foreign_key: :moderator_id,
    class_name: :Sub

  has_many :posts,
    primary_key: :id,
    foreign_key: :user_id,
    class_name: :Post

  def ensure_session_token
    self.session_token = SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    ensure_session_token
    self.save!
    self.session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest) == password
  end

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    user && user.is_password?(password) ? user : nil
  end
end

RedditOnRails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :require_login, :current_user, :logged_in?

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end
end

RedditOnRails/app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :require_login

  def show
    @post = Post.find(params[:id])
    render :show
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.save

      params[:post][:sub_ids].each do |sub_id|
        PostSub.create!(post_id: @post.id, sub_id: sub_id)
      end

      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to new_post_url
    end
  end

  def edit
    @post = current_user.posts.find(params[:id])
  end

  def update
    @post = current_user.posts.find(params[:id])

    if @post.update(post_params)
      redirect_to post_url(@post)
    else
      flash[:errors] = @post.errors.full_messages
      redirect_to post_url(@post)
    end
  end

  def destroy
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :content, :sub_ids)
  end
end

RedditOnRails/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])

    if @user
      login(@user)
      redirect_to subs_url
    else
      flash[:errors] = ["Invalid Credentials"]
      render :new
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

RedditOnRails/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  before_action :require_current_owner, only: [:edit, :update]

  def index
    @subs = Sub.all
    render :index
  end

  def new
  end

  def create
    @sub = Sub.new(sub_params)
    @sub.moderator_id = current_user.id

    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to new_sub_url
    end
  end

  def show
    @sub = Sub.find(params[:id])
  end

  def edit
  end

  def update
    @sub = current_user.subs.find(params[:id])

    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash[:errors] = @sub.errors.full_messages
      redirect_to edit_sub_url
    end
  end

  def destroy
  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end

  def require_current_owner
    @sub = Sub.find(params[:id])
    redirect_to sub_url(@sub) unless current_user == @sub.moderator
  end

end

RedditOnRails/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to subs_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

RedditOnRails/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    '<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">'.html_safe
  end
end

RedditOnRails/app/helpers/posts_helper.rb
module PostsHelper
end

RedditOnRails/app/helpers/session_helper.rb
module SessionHelper
end

RedditOnRails/app/helpers/subs_helper.rb
module SubsHelper
end

RedditOnRails/app/helpers/users_helper.rb
module UsersHelper
end

RedditOnRails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RedditOnRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <link href="https://fonts.googleapis.com/css?family=Rammetto+One" rel="stylesheet">
  </head>


    <header>
      <% if logged_in? %>
        <a href="<%= subs_url %>">All subs</a>

        <div class="user_stuff">
          Logged in as: <%= current_user.username %>
          <form action="<%= session_url %>" method="post">
            <%= auth_token %>
            <input type="hidden" name="_method" value="DELETE">
            <input type="submit" name="" value="Sign Out">
          </form>
        </div>
      <% else %>

          <a href="<%= new_user_url %>">Join Da Krew!</a>
          <a href="<%= new_session_url %>">Welcome Back!</a>

      <% end %>
    </header>

    <%= flash[:errors].try(:each) {|err| err} %>

    <!-- <a href="<%= posts_url %>">All posts</a> -->
    <body>
    <%= yield %>
  </body>
</html>

RedditOnRails/app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

RedditOnRails/app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

RedditOnRails/app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<form class="" action="<%= post_url(@post) %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= auth_token %>

  <label>Title
    <input type="text" name="post[title]" value="<%= @post.title %>">
  </label><br>

  <label>Url
    <input type="text" name="post[url]" value="<%= @post.url %>">
  </label><br>

  <label>Content
    <input type="text" name="post[content]" value="<%= @post.content %>">
  </label><br>

  <% Sub.all.each do |sub_topic| %>
    <label>
      <input
        type="checkbox"
        name="post[sub_ids][]"
        value="<%= sub_topic.id %>"
        <%= "checked" if @post.subs.include?(sub_topic) %> >
      <%= sub_topic.title %><br>
    </label>
  <% end %>

  <input type="submit" name="" value="Whatchu talkin bout' Willis">

</form>

RedditOnRails/app/views/posts/new.html.erb
<h1>New Post</h1>

<form class="" action="<%= posts_url %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="text" name="post[title]" value="">
  </label><br>

  <label>Url
    <input type="text" name="post[url]" value="">
  </label><br>

  <label>Content
    <input type="text" name="post[content]" value="">
  </label><br>

  <% Sub.all.each do |sub_topic| %>
    <label>
      <input type="checkbox" name="post[sub_ids][]" value="<%= sub_topic.id %>">
      <%= sub_topic.title %><br>
    </label>
  <% end %>

  <input type="submit" name="" value="Whatchu talkin bout' Willis">

</form>

RedditOnRails/app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<p>Find me in app/views/posts/show.html.erb</p>

<% @post.subs.each do |sub| %>
  <a href='<%= sub_url(sub) %>'><%= sub.title %>
  </a>

<% end %>

RedditOnRails/app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

RedditOnRails/app/views/subs/create.html.erb
<h1>Subs#create</h1>
<p>Find me in app/views/subs/create.html.erb</p>

RedditOnRails/app/views/subs/destroy.html.erb
<h1>Subs#destroy</h1>
<p>Find me in app/views/subs/destroy.html.erb</p>

RedditOnRails/app/views/subs/edit.html.erb
<h1>Subs#edit</h1>
<p>Find me in app/views/subs/edit.html.erb</p>

RedditOnRails/app/views/subs/index.html.erb
<h1>All dem subs</h1>

<img src="/assets/subpic.jpg" alt="">
<% @subs.each do |sub| %>
  <li>
    <a href="<%= sub_url(sub) %>"><%= sub.title %></a>
  </li>
<% end %>

<p>
  <a href="<%= new_sub_url %>">Create New SAMMY</a>
</p>

RedditOnRails/app/views/subs/new.html.erb
<h1>New Sub</h1>

<form class="" action="<%= subs_url %>" method="post">
  <%= auth_token %>

  <label>Title
    <input type="text" name="sub[title]" value="">
  </label><br>

  <label>Description
    <input type="text" name="sub[description]" value="">
  </label><br>

  <input type="submit" name="" value="Much wow, lookatchu so smarticles">

</form>

RedditOnRails/app/views/subs/show.html.erb
<h1>Show Off Dat Sub</h1>

<% @sub.posts.each do |post| %>
  <p>
    <label>Title:
      <a href="<%= post_url(post) %>">
        <%= post.title %>
      </a>
    </label><br>

    <label>URL:
      <%= post.url %>
    </label><br>

    <label>Content:
      <%= post.content %>
    </label>
  </p>
<% end %><br>

<a href="<%= new_post_url %>">Create New Post</a>

RedditOnRails/app/views/subs/update.html.erb
<h1>Subs#update</h1>
<p>Find me in app/views/subs/update.html.erb</p>

RedditOnRails/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

RedditOnRails/app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

RedditOnRails/app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

RedditOnRails/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

RedditOnRails/app/views/users/new.html.erb
<h1>Sign Up!</h1>

<form class="" action="<%= users_url %>" method="post">
  <%= auth_token %>

  <label>Username
    <input type="text" name="user[username]" value="">
  </label>

  <label>Password
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="ONE OF US!">

</form>

RedditOnRails/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

RedditOnRails/app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>